server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/library?serverTimezone=GMT%2B8
    username: root
    password: 123456
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    username: 2486859520@qq.com
    password: tpwbrouabkmjecfa
  servlet:
    multipart:
      max-file-size: 10MB  		# 设置单个文件最大大小为10MB
      max-request-size: 100MB  	# 设置多个文件大小为100MB


mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/Mapper/*.xml



